I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script call
    call chapter1
  File "game/chapter1.rpy", line 34, in script
    if not povname:
  File "game/chapter1.rpy", line 34, in <module>
    if not povname:
NameError: name 'povname' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script call
    call chapter1
  File "game/chapter1.rpy", line 34, in script
    if not povname:
  File "F:\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "F:\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "F:\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chapter1.rpy", line 34, in <module>
    if not povname:
NameError: name 'povname' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Orin 1.0
Fri Nov 20 23:24:18 2020
